version: '3'
services:
  db:
    image: postgres:10.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: sample_app_docker_development
  web:
    build: ../../
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ../../:/myapp
    environment:
      RAILS_ENV: "development"
      REDIS_URL: "redis://redis:6379/12"
      DATABASE_HOST: "db"
    ports:
      - "3000:3000"
    depends_on:
      - db
